GH-580: test for data_directory_from_context with opt dir and implementation … (#248)
* test for data_directory_from_context with opt dir and implementation in fn

* fixed naming and optimizing call for add_chain_specific_directories()

* add_chain_specific_directories to tests in  bootstrapper.rs, mod.rs, node_configuraton_standard.rs

* calculate_configured_setup returns None -> panicked at 'called  on a  value'

* formatting

* cleaning misstake

* commit changes - move to laptop

* fix tests failing on the chain specific data direcotry

* changes based on Berts review comments

* formatting

* remove todo causing crash

* half way to fix cleanup_after_deceased_clients_integration

* failing on creating log file in node_logs_panic_integration

* change joins for add_chain_specific_directories fn

* remove unused import

* add_chain_specific_directories moved to masq_lib::utils, introduced new function node_chain_specific_directory for multinode tests

* remove comments

* remove comments, replace joins wtih add_chain_specific_directories fn, test for chain specific directories uncompleted but passing

* Revert "remove unused import"

This reverts commit c0f205a2cd6c5ecb1d53e48cf2763ffacd1455f4.

* pull and resolve conflicts

* vec! with foreach for test server_initializer_collected_params_senses_when_user_specifies_data_directory_without_chain_specific_directory

* add more scenarios for test with custom data_directory_opt in test server_initializer_collected_params_senses_when_user_specifies_data_directory_without_chain_specific_directory

* continue of solving Bert's comments, start of modifying UI to show full path for user specified data-directory

* try to retrieve chain-name from inner.values

* chain_name collecting with map().collect, value_value collecting with match

* move match for value_value to separate fn to clar dump_setup

* chainge test for right fn calls, added message about changed data-directory to match chain parameter

* change of chain_specific_data_directory to add alway chain_specific_dir to path set by user, so chain dir could be duplicated, finalize test for masq UI to check various UiSetupResponsValueStatus

* new integration test for specific data_directory ensure_data_directory_has_specific_chain_direcotry_within

* fix Default arm for directory path enrichment with chain specific directory

* integration test to ensure setup command do the right job to add chain specific directory

* change data-directory, comparsion and panic messages in chain_specific_directory_test_integration test, remove comments inn setup_command

* fix formatting for expected in chain_specific_directory test, remove unused import from setup_command

* finalize test for setup_reporter calculate_fundamentals_with_chain_specific_dir

* commented code to test in linux

* compilable version to test in linux

* move changes to desktop

* for bert from my linux machine

* GH-580: showing the right direction

* fixing more tests

* GH-580: ongoing repairment in setup_reporter

* GH-580: fixed data directory niches that were causing a lot of troubles

* remove unvanted println

* formatting

* fixed test calculate_setup_with_chain_specific_dir to pass on mac, resolved last Berts comments

* remove unused imports and chain from mock node

* remove unused code from setup_command

* resolving review comments - add closure for retriving data-dir and chain

* resolving comments: cleaning setup_command tests, cleaning setup_reporter:get_modified_setup, fix misspe<lls

* try to send less data to determine_setup_value_of_set_data_directory fn

* remove unused data from SetupReporterReal::determine_setup_value_of_set_data_directory

* formatting

* fixed test for get_modified_setup::get_modified_setup_user_specified_data_directory_depends_on_new_chain_on_success

* resolved review comments on ensure_data_directory_has_specific_chain_directory_within_integration test

* split of test calculate_setup_with_chain_specific_dir into two separate tests

* resolving review comments, renaming, optimization, fixing tests

* resolving review comments - mainly renaming

* Half way to get rid of DirsWrapper from go fn in DumpConfigRunnerReal

* remove DirsWrapper from arguments to DumpConfigRunner for DumpConfigRunnerReal

* fixed windows tests for determine_fundamentals

* renaming functions, removing TODOs and removing unnecesary attributes from test

* fixed node_chain_specific_data_directory and impl MASQRealNode plus try to fix node_creates_log_file_with_heading_integration - continue next

* fixed node_creates_log_file_with_heading_integration

* remove unused import and debug print, tests failing in ci/all.sh but passing when run from cmd line

* fix paths in tests for windows: setup_reporter

* fix windows paths for test server_initializer_collected_params_senses_when_user_specifies_data_directory_without_chain_specific_directory

* fix setup_command and broadcast_handler tests: added missing data-directory and chain parameters to config

* setup_command removign ropsten and correcting UiResponseValue, broadcast_handler: removing unwanted piece of code, shared_schema: DATA_DIRECTORY_HELP, setup_reporter: fix test

* correction of DATA_DIRECTORY_HELP

* lazy_static for STANDARD_ARG_LIST in shared_schema

* separate help for --data-directory in Node, Config Dump and UI

* remove duplication of data-directory clap app argument, add dirs to masq_lib to compute static constant DATA_DIRECTORY_DAEMON_HELP, fix broadcast_hadnler test

* move data-directory back to shared schema::shared_app::head

* remove typo misstake

* apply Dans comments on review 6, put code in the order, formatting and moving code thru directories and files

* remove unused import

* resolve DATA_DIRECTORY_DAEMON_HELP for masq UI

---------

Co-authored-by: Vojtěch Parkán <vojtechparkan@Vojtechs-iMac.home>
Co-authored-by: Vojtěch Parkán <vojtechparkan@Vojtechs-iMac.local>
Co-authored-by: Vojtěch Parkán <czarte@gmail.com>
Co-authored-by: Bert <Bert@Bert.com>